### ISSUE TITLE
Problems with Threshold

### ISSUE THREAD

**Issue by kocsismhly** [SEPM-Group-6/Frontend#1]
The input field for threshold should only allow digits.

**Comment by SamuelKollar** [comment]
what other types does it allow, I tried letters but they dont work.

**Comment by kocsismhly** [comment]
It's accepting letters for me.
<img width="1502" alt="Screenshot 2023-12-10 at 5 19 08 PM" src="https://github.com/SEPM-Group-6/Frontend/assets/89989799/fd157a17-10bd-43b6-963b-b67efb14d0ec">

**Comment by SamuelKollar** [comment]
are you using safari ?

**Comment by kocsismhly** [comment]
I just checked, it's good on Edge or Chrome, but not on Safari or Firefox.  It's alright then.

**Comment by SamuelKollar** [comment]
okay, I mean we are going to be presenting so we can just write numbers and it should be alright.
